---
# This playbook will generate and apply configuration to all of the devices

- include: pb.config.all.yaml

- name: Apply configuration
  hosts: juniper
  connection: local
  gather_facts: false
  roles:
  - Juniper.junos
  tasks:
  - name: Pushing config ... please wait
    juniper_junos_config:
      load: "merge"
      src: "{{ junos_conf }}"
    register: response
  - name: Print the response
    debug:
      var: response
