underlay:
    local:
        asn: 60001
    neighbors:
      - interface: xe-0/0/0
        name: vqfx-spine-01
        asn: 60011
        peer_ip: 172.20.0.10
        local_ip: 172.20.0.11
      - interface: xe-0/0/1
        name: vqfx-spine-02
        asn: 60011
        peer_ip: 172.20.0.20
        local_ip: 172.20.0.21
